// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABLcsQg6j28-LWSPPaRO7AdZ_kdhFn8Co',
    appId: '1:592656389284:web:99f780037d02fbf246c231',
    messagingSenderId: '592656389284',
    projectId: 'chatappmitch-59882',
    authDomain: 'chatappmitch-59882.firebaseapp.com',
    storageBucket: 'chatappmitch-59882.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlyv1eaG60XvcedwsqHUBQy5CqmGiQ6M0',
    appId: '1:592656389284:android:f84de1f2bd1c0ae746c231',
    messagingSenderId: '592656389284',
    projectId: 'chatappmitch-59882',
    storageBucket: 'chatappmitch-59882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE4e7sw-_T7yUaGNDyGLvUuv8bGQTozZI',
    appId: '1:592656389284:ios:522d78006086a74a46c231',
    messagingSenderId: '592656389284',
    projectId: 'chatappmitch-59882',
    storageBucket: 'chatappmitch-59882.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE4e7sw-_T7yUaGNDyGLvUuv8bGQTozZI',
    appId: '1:592656389284:ios:522d78006086a74a46c231',
    messagingSenderId: '592656389284',
    projectId: 'chatappmitch-59882',
    storageBucket: 'chatappmitch-59882.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABLcsQg6j28-LWSPPaRO7AdZ_kdhFn8Co',
    appId: '1:592656389284:web:adac9faab151bf8946c231',
    messagingSenderId: '592656389284',
    projectId: 'chatappmitch-59882',
    authDomain: 'chatappmitch-59882.firebaseapp.com',
    storageBucket: 'chatappmitch-59882.appspot.com',
  );
}
